#!/usr/bin/env python3
"""Phase 1, wave 2: 250 more ideas, scored with the same formula as ops.py.

Estimates are category defaults adjusted by a strength tier, not market research. Tier:
  A = dated UK rule change or clear pain + reuses our engines; B = solid; C = weak/saturated;
  X = conflicts with hard rules or UK law (never built; reason given).
Writes ops/data/ideas_wave2.csv and prints the ranking.
"""
import csv
from pathlib import Path

from ops import score_idea

# category: (setup_cash, owner_hours, monthly_run, fee_pct, rev_mid by tier A/B/C, p by tier A/B/C, weeks)
CAT = {
    "free tool":       (0, 0.5, 0, 0.00, (40, 20, 8),    (0.35, 0.25, 0.12), 4),   # revenue = referred sales
    "spreadsheet":     (0, 1,   0, 0.02, (160, 80, 25),  (0.30, 0.20, 0.08), 2),
    "printable/guide": (0, 1,   0, 0.02, (60, 30, 10),   (0.25, 0.15, 0.06), 2),
    "site check":      (0, 1,   2, 0.02, (200, 100, 30), (0.25, 0.15, 0.06), 3),
    "service":         (0, 10,  5, 0.02, (300, 150, 60), (0.15, 0.10, 0.05), 4),
    "dev tool":        (0, 1,   0, 0.00, (30, 15, 5),    (0.25, 0.15, 0.08), 6),
    "micro-SaaS (AI)": (10, 6,  25, 0.03, (250, 120, 40), (0.15, 0.10, 0.04), 8),
    "content":         (0, 3,   0, 0.00, (60, 30, 10),   (0.15, 0.08, 0.04), 12),
}

IDEAS = [
    # ---- free tools (drive traffic to paid products) ----
    ("MTD for Income Tax eligibility checker", "free tool", "A"),
    ("Late-payment interest + compensation calculator (UK B2B)", "free tool", "A"),
    ("HMRC mileage allowance calculator (45p/25p)", "free tool", "A"),
    ("VAT Flat Rate Scheme vs standard calculator", "free tool", "A"),
    ("VAT registration threshold (rolling 12-month) checker", "free tool", "A"),
    ("Use-of-home flat rate calculator", "free tool", "B"),
    ("Self Assessment payments on account calculator", "free tool", "A"),
    ("Dividend vs salary calculator for company directors 2026-27", "free tool", "B"),
    ("Trading allowance (£1,000) vs actual expenses checker", "free tool", "B"),
    ("Property allowance vs actual expenses checker", "free tool", "B"),
    ("Rent increase (Section 13) date planner", "free tool", "B"),
    ("Deposit protection 30-day deadline calculator", "free tool", "B"),
    ("Gas safety / EICR renewal date calculator", "free tool", "B"),
    ("Invoice due-date and payment-terms calculator", "free tool", "C"),
    ("UK working-days calculator (bank holidays)", "free tool", "C"),
    ("Pro-rata salary calculator", "free tool", "C"),
    ("Holiday entitlement calculator (5.6 weeks)", "free tool", "B"),
    ("Statutory redundancy pay calculator", "free tool", "C"),
    ("Capital allowances (AIA) quick estimator", "free tool", "C"),
    ("Hourly rate calculator for freelancers", "free tool", "B"),
    ("Markup vs margin calculator", "free tool", "C"),
    ("Break-even calculator for small shops", "free tool", "C"),
    ("Cash-runway calculator", "free tool", "C"),
    ("Student loan repayment on self-employment estimator", "free tool", "C"),
    ("Class 2/Class 4 NI explainer calculator", "free tool", "B"),
    ("High income child benefit charge calculator", "free tool", "C"),
    ("Personal allowance taper (£100k) calculator", "free tool", "B"),
    ("EPC minimum rating checker for landlords", "free tool", "C"),
    ("HMO licence need checker (England)", "free tool", "C"),
    ("WCAG colour-contrast checker", "free tool", "C"),
    ("Cookie banner self-check questionnaire", "free tool", "C"),
    ("Invoice legal-fields checker (UK)", "free tool", "B"),
    ("Price-per-unit display checker for online shops", "free tool", "C"),
    ("Tax-year date converter (6 April)", "free tool", "C"),
    ("MTD quarterly deadline calendar export (.ics)", "free tool", "A"),
    # ---- spreadsheets / templates ----
    ("MTD for landlords property income workbook", "spreadsheet", "A"),
    ("MTD workbook for sole trader + landlord combined", "spreadsheet", "A"),
    ("Joint-owned property income split workbook", "spreadsheet", "B"),
    ("Furnished holiday let transition tracker (post-2025 abolition)", "spreadsheet", "B"),
    ("Section 24 finance-cost restriction estimator", "spreadsheet", "B"),
    ("Rent arrears tracker with Section 8 ground dates", "spreadsheet", "B"),
    ("HMO room-by-room compliance tracker", "spreadsheet", "B"),
    ("Scotland landlord compliance tracker", "spreadsheet", "B"),
    ("Wales landlord compliance tracker (Renting Homes Act)", "spreadsheet", "B"),
    ("Airbnb/short-let income and expense tracker", "spreadsheet", "B"),
    ("CIS subcontractor deductions tracker", "spreadsheet", "A"),
    ("CIS monthly return prep workbook for contractors", "spreadsheet", "B"),
    ("Payroll-lite workbook for one employee (RTI prep)", "spreadsheet", "C"),
    ("Pension auto-enrolment duties tracker", "spreadsheet", "C"),
    ("Company director loan account tracker", "spreadsheet", "B"),
    ("Limited company dividend voucher + minutes templates", "spreadsheet", "B"),
    ("Confirmation statement and accounts deadline tracker", "spreadsheet", "B"),
    ("Corporation Tax marginal relief estimator", "spreadsheet", "B"),
    ("VAT return prep workbook (standard scheme)", "spreadsheet", "B"),
    ("Cash-accounting VAT scheme workbook", "spreadsheet", "C"),
    ("Domestic reverse charge (construction VAT) invoice kit", "spreadsheet", "A"),
    ("Etsy seller income + fees reconciler", "spreadsheet", "B"),
    ("eBay/Vinted seller HMRC reporting-rules tracker", "spreadsheet", "A"),
    ("Amazon FBA fee and profit calculator workbook", "spreadsheet", "C"),
    ("Shopify monthly P&L template", "spreadsheet", "C"),
    ("Freelancer client-profitability tracker", "spreadsheet", "C"),
    ("Time-tracking + invoicing workbook", "spreadsheet", "C"),
    ("Job costing sheet for tradespeople", "spreadsheet", "B"),
    ("Materials price-book for builders", "spreadsheet", "C"),
    ("Van running-costs vs mileage comparison", "spreadsheet", "B"),
    ("Hairdresser/beauty chair-rental income tracker", "spreadsheet", "B"),
    ("Childminder income and expenses workbook", "spreadsheet", "B"),
    ("Driving instructor business workbook", "spreadsheet", "C"),
    ("Personal trainer client + income tracker", "spreadsheet", "C"),
    ("Musician/performer gig income tracker", "spreadsheet", "C"),
    ("Photographer job and kit depreciation workbook", "spreadsheet", "C"),
    ("Cleaner rounds and invoicing workbook", "spreadsheet", "B"),
    ("Dog walker/pet sitter booking + income sheet", "spreadsheet", "C"),
    ("Tutor lessons and income tracker", "spreadsheet", "C"),
    ("Charity/club treasurer accounts workbook", "spreadsheet", "B"),
    ("Community interest company (CIC) report prep", "spreadsheet", "C"),
    ("Grant budget tracker for small charities", "spreadsheet", "C"),
    ("Tenancy deposit dispute evidence log", "spreadsheet", "B"),
    ("Property maintenance schedule (landlords)", "spreadsheet", "B"),
    ("Service-charge budget for small leaseholds", "spreadsheet", "C"),
    ("Home-business insurance renewal tracker", "spreadsheet", "C"),
    ("Subscription/software cost audit sheet", "spreadsheet", "C"),
    ("Business budget vs actual (12 months)", "spreadsheet", "C"),
    ("Debtors ageing report template", "spreadsheet", "B"),
    ("Stock/inventory tracker for makers", "spreadsheet", "C"),
    ("Price increase planner (inflation pass-through)", "spreadsheet", "C"),
    ("Sole trader to limited company comparison model", "spreadsheet", "B"),
    ("Side-hustle HMRC £1,000 allowance tracker", "spreadsheet", "A"),
    ("Crypto trading-income vs gains record sheet", "spreadsheet", "B"),
    ("Rent-a-room scheme (£7,500) tracker", "spreadsheet", "B"),
    ("Making Tax Digital digital-links checker sheet", "spreadsheet", "C"),
    ("Year-end accountant handover pack", "spreadsheet", "B"),
    ("Receipt log with HMRC categories (mobile-friendly)", "spreadsheet", "B"),
    ("Company car vs mileage allowance comparison", "spreadsheet", "C"),
    # ---- printables / guides ----
    ("Renters' Rights Act landlord guide (plain English)", "printable/guide", "A"),
    ("Section 8 possession grounds quick reference", "printable/guide", "B"),
    ("New landlord first-let checklist (England)", "printable/guide", "A"),
    ("Tenant move-in/move-out inventory template", "printable/guide", "B"),
    ("MTD quick-start one-pager (laminate-ready)", "printable/guide", "B"),
    ("Self-employed tax year checklist 2026-27", "printable/guide", "B"),
    ("Starting a sole trader business checklist", "printable/guide", "B"),
    ("Setting up a limited company checklist", "printable/guide", "C"),
    ("Allowable expenses A–Z for tradespeople", "printable/guide", "B"),
    ("Allowable expenses A–Z for online sellers", "printable/guide", "B"),
    ("Allowable expenses A–Z for landlords", "printable/guide", "B"),
    ("Getting paid on time: letter templates pack", "printable/guide", "B"),
    ("Small claims court (money claim online) walkthrough", "printable/guide", "B"),
    ("Terms and conditions starter for tradespeople", "printable/guide", "C"),
    ("GDPR basics for sole traders (ICO fee, privacy notice)", "printable/guide", "B"),
    ("Privacy notice template for small websites", "printable/guide", "C"),
    ("Accessibility statement template (EAA-ready)", "printable/guide", "B"),
    ("Consumer rights refunds cheat sheet for shops", "printable/guide", "B"),
    ("Fake review ban (DMCC Act) compliance guide for shops", "printable/guide", "A"),
    ("Drip pricing rules (DMCC Act) guide for online sellers", "printable/guide", "A"),
    ("Subscription contracts rules guide (DMCC Act)", "printable/guide", "B"),
    ("Price marking and unit pricing guide", "printable/guide", "C"),
    ("Food business registration checklist", "printable/guide", "C"),
    ("Market trader/craft fair checklist", "printable/guide", "C"),
    ("Home-based business planning permission explainer", "printable/guide", "C"),
    ("Employing your first person checklist", "printable/guide", "B"),
    ("Right to work checks guide for employers", "printable/guide", "C"),
    ("Minimum wage 2026 rates poster", "printable/guide", "C"),
    ("Year planner 2027-28 (next edition)", "printable/guide", "B"),
    ("Weekly admin planner for sole traders", "printable/guide", "C"),
    ("Cash-flow crisis 7-day plan", "printable/guide", "C"),
    ("Pricing your services worksheet", "printable/guide", "C"),
    ("Client onboarding checklist for freelancers", "printable/guide", "C"),
    ("Quote follow-up email scripts", "printable/guide", "C"),
    ("Scam and invoice-fraud warning signs poster", "printable/guide", "B"),
    ("Cyber Essentials readiness checklist", "printable/guide", "B"),
    ("Business continuity one-page plan", "printable/guide", "C"),
    ("Energy-saving checklist for small premises", "printable/guide", "C"),
    ("Landlord tenant-communication templates pack", "printable/guide", "B"),
    ("Pet request response templates (RRA)", "printable/guide", "B"),
    # ---- site checks ----
    ("Broken-link and 404 report", "site check", "B"),
    ("Mobile-friendliness report", "site check", "C"),
    ("Page-speed report with plain-English fixes", "site check", "B"),
    ("SEO basics audit (titles, meta, headings, sitemap)", "site check", "B"),
    ("Security headers and HTTPS check", "site check", "B"),
    ("Email deliverability check (SPF, DKIM, DMARC)", "site check", "A"),
    ("Shop legal-info check (trader identity, returns, T&Cs)", "site check", "A"),
    ("Drip-pricing check for checkout pages (DMCC)", "site check", "B"),
    ("Image alt-text audit", "site check", "C"),
    ("Form accessibility audit", "site check", "B"),
    ("Accessibility re-scan monitoring (monthly)", "site check", "B"),
    ("Cookie re-check after site changes (monthly)", "site check", "C"),
    ("Domain and SSL expiry monitoring for agencies", "site check", "C"),
    ("Third-party script inventory report", "site check", "C"),
    ("Privacy-policy vs actual trackers comparison", "site check", "B"),
    ("Structured data (schema) check for local businesses", "site check", "C"),
    ("Google Business Profile completeness check", "site check", "C"),
    ("PDF accessibility check", "site check", "C"),
    ("Readability (plain English) score report", "site check", "C"),
    ("Checkout accessibility check for Shopify", "site check", "B"),
    # ---- services ----
    ("Email authentication setup (SPF/DKIM/DMARC)", "service", "A"),
    ("Accessibility statement writing service", "service", "B"),
    ("Cookie consent fix service", "service", "B"),
    ("Website legal pages review and rewrite", "service", "B"),
    ("Google Business Profile optimisation", "service", "B"),
    ("Spreadsheet clean-up and automation", "service", "B"),
    ("MTD bridging setup help (records only, no filing)", "service", "B"),
    ("Etsy shop listing refresh", "service", "C"),
    ("Newsletter setup for small businesses", "service", "C"),
    ("Website migration to static hosting (cost cut)", "service", "B"),
    ("Online booking system setup", "service", "C"),
    ("Invoice and payment-reminder automation", "service", "B"),
    ("Microsoft 365 / Google Workspace tidy-up", "service", "C"),
    ("Small charity website accessibility fixes", "service", "B"),
    ("Menu and allergen info digitisation for cafés", "service", "C"),
    ("Product photo background clean-up (licensed images only)", "service", "C"),
    ("Plain-English rewrite of policies and FAQs", "service", "B"),
    ("Translation review coordination (native reviewers)", "service", "C"),
    ("Data export and backup setup", "service", "C"),
    ("Dashboard for landlords (rent roll, arrears)", "service", "B"),
    # ---- dev tools ----
    ("GitHub Action: accessibility scan on pull requests", "dev tool", "A"),
    ("GitHub Action: broken-link checker", "dev tool", "B"),
    ("GitHub Action: cookie-before-consent check", "dev tool", "B"),
    ("CLI: UK bank holiday data (gov.uk JSON) helper", "dev tool", "C"),
    ("npm package: UK tax-year date utilities", "dev tool", "C"),
    ("npm package: UK VAT number format validator", "dev tool", "C"),
    ("npm package: UK postcode format validator", "dev tool", "C"),
    ("Static site starter with legal pages + accessibility", "dev tool", "B"),
    ("Invoice PDF generator (HTML template)", "dev tool", "C"),
    ("Conventional-commit linter (tiny)", "dev tool", "C"),
    ("Sitemap generator for static sites", "dev tool", "C"),
    ("Pages deploy template with build gating", "dev tool", "C"),
    ("Uptime monitor: Slack/Discord alerts add-on", "dev tool", "C"),
    ("ICS calendar generator for tax deadlines", "dev tool", "B"),
    ("Accessibility report PDF template (open source)", "dev tool", "C"),
    # ---- micro-SaaS needing AI tokens (blocked until budget + key) ----
    ("Receipt photo to categorised CSV", "micro-SaaS (AI)", "B"),
    ("Review-reply drafts for genuine reviews", "micro-SaaS (AI)", "B"),
    ("Plain-English explainer for HMRC letters", "micro-SaaS (AI)", "A"),
    ("Tenancy agreement plain-English summariser", "micro-SaaS (AI)", "B"),
    ("Bank statement to HMRC-category classifier", "micro-SaaS (AI)", "A"),
    ("Accessibility alt-text suggestions (owner approves)", "micro-SaaS (AI)", "B"),
    ("Policy/FAQ writer from owner facts", "micro-SaaS (AI)", "C"),
    ("Quote-writing assistant for trades", "micro-SaaS (AI)", "C"),
    ("Job-ad writer with discrimination-law checks", "micro-SaaS (AI)", "C"),
    ("Invoice data extraction API", "micro-SaaS (AI)", "C"),
    ("Product-description writer (facts in, no invented claims)", "micro-SaaS (AI)", "C"),
    ("Customer email triage for small shops", "micro-SaaS (AI)", "C"),
    ("Meeting-notes to action list", "micro-SaaS (AI)", "C"),
    ("Podcast transcript + show notes", "micro-SaaS (AI)", "C"),
    ("Grant application first-draft helper", "micro-SaaS (AI)", "C"),
    # ---- content ----
    ("The Deadline newsletter: paid 'landlord edition'", "content", "B"),
    ("Monthly UK rule-change digest for accountants", "content", "B"),
    ("Plain-English MTD FAQ hub (hand-written)", "content", "A"),
    ("Renters' Rights Act FAQ hub", "content", "A"),
    ("DMCC Act consumer-law FAQ hub for shops", "content", "B"),
    ("EAA accessibility FAQ hub for UK exporters", "content", "B"),
    ("Case studies of our own tools (build-in-public log)", "content", "C"),
    ("Tax-year-end email course (5 emails)", "content", "B"),
    ("Landlord email course (7 emails)", "content", "B"),
    ("Accessibility fixes email course for shop owners", "content", "C"),
    ("Glossary of UK tax terms for sole traders", "content", "B"),
    ("Templates gallery (free samples) for SEO", "content", "B"),
    ("Quarterly 'what changed' report PDF", "content", "C"),
    ("Podcast-style audio summaries (disclosed AI voice)", "content", "C"),
    ("Comparison pages of HMRC-recognised MTD software (no affiliate)", "content", "B"),
    ("Making Tax Digital penalty points tracker", "spreadsheet", "B"),
    ("Landlord MTD quarterly deadline wall planner", "printable/guide", "B"),
    ("Renters' Rights Act information-sheet delivery log", "spreadsheet", "B"),
    ("Awaab's Law repairs response-time tracker (social landlords)", "spreadsheet", "C"),
    ("Online marketplace seller 'trader or hobbyist' checker", "free tool", "B"),
    ("UK bank holiday + tax deadline calendar feed", "free tool", "B"),
    ("Accessibility quick-wins workshop (recorded, 1 hour)", "content", "C"),
    ("Freelancer IR35 status record sheet (records only)", "spreadsheet", "C"),
    ("Business mileage log (printable)", "printable/guide", "B"),
    ("Small shop DMCC Act compliance check", "site check", "B"),
    ("Invoice template variants for 10 trades (one kit, not 10 listings)", "spreadsheet", "C"),
    # ---- rejected: conflict with hard rules or UK law ----
    ("Bulk AI blog network for ad revenue", "content", "X", "Scaled low-value AI content: spam (hard rule 1)"),
    ("Buying/selling reviews or star ratings", "service", "X", "Illegal under DMCC Act 2024 (hard rule 1)"),
    ("Social media follower/engagement packages", "service", "X", "Fake engagement (hard rule 1)"),
    ("Scraped property or business contact lists", "micro-SaaS (AI)", "X", "Scraping + UK GDPR/PECR (hard rule 1)"),
    ("Cold-email blasting service", "service", "X", "PECR consent rules; spam (hard rule 1)"),
    ("Tax return filing for clients", "service", "X", "Needs AML supervision and professional indemnity"),
    ("Bookkeeping for clients", "service", "X", "Needs AML supervision (UK law)"),
    ("Legal document drafting for consumers", "service", "X", "Reserved legal activities / liability"),
    ("Investment or crypto trading signals", "content", "X", "FCA-regulated financial promotion"),
    ("Crypto payment processing for other merchants", "micro-SaaS (AI)", "X", "FCA cryptoasset registration required"),
    ("AI-written ebooks mass-uploaded to Amazon KDP", "printable/guide", "X", "Mass AI content against KDP rules (hard rule 1)"),
    ("Print-on-demand designs from copyrighted characters", "printable/guide", "X", "Copyright infringement (hard rule 1)"),
    ("Resold 'PLR' content packs", "printable/guide", "X", "Low value, duplicate content (hard rule 1)"),
    ("Impersonation-style 'official' HMRC form services", "service", "X", "Misleading, impersonates government (hard rule 1)"),
    ("Website accessibility overlay widget sold as 'compliance'", "micro-SaaS (AI)", "X", "Misleading compliance claim (hard rule 1)"),
    ("Essay/coursework writing for students", "service", "X", "Contract cheating is illegal in England (Skills and Post-16 Education Act 2022)"),
    ("Auto-generated YouTube Shorts channels", "content", "X", "Repetitious AI content, demonetisation (hard rule 1)"),
    ("Dropshipping with unverified product claims", "service", "X", "Misleading claims (hard rule 1)"),
    ("Airdrop/'earn crypto' referral schemes", "content", "X", "Misleading promotion (hard rule 1)"),
    ("Web scraping-as-a-service", "micro-SaaS (AI)", "X", "Breaches site ToS (hard rule 1)"),
]


def rows():
    out = []
    for i, item in enumerate(IDEAS, 1):
        name, cat, tier = item[:3]
        reason = item[3] if len(item) > 3 else ""
        setup, hours, run, fee, revs, ps, weeks = CAT[cat]
        k = "ABC".index(tier) if tier in "ABC" else 2
        idea = {"id": f"W{i:03d}", "name": name, "category": cat, "tier": tier,
                "setup_cash_gbp": setup, "owner_hours": hours, "monthly_run_gbp": run, "fee_pct": fee,
                "rev_mid": revs[k], "p_success": ps[k] if tier != "X" else 0, "weeks_to_first_rev": weeks,
                "platform_risk": "H" if tier == "X" else "L",
                "blocked_on": "Anthropic API key + budget" if cat == "micro-SaaS (AI)" and tier != "X" else "",
                "rejected_reason": reason}
        idea.update(score_idea(idea))
        if tier == "X":
            idea["score"] = 0.0
        out.append(idea)
    return out


if __name__ == "__main__":
    data = rows()
    path = Path(__file__).resolve().parent / "data" / "ideas_wave2.csv"
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(data[0].keys()))
        w.writeheader()
        w.writerows(data)
    ranked = sorted(data, key=lambda r: r["score"], reverse=True)
    print(f"{len(data)} ideas -> {path}")
    print("tiers:", {t: sum(r['tier'] == t for r in data) for t in "ABCX"})
    for r in ranked[:15]:
        print(f"{r['id']} {r['score']:.2f} {r['tier']} {r['category']:16} {r['name']}")
